'use client';

import React from 'react';
import { FileText, Calendar, ArrowRight, Download, Share2 } from 'lucide-react';
import Link from 'next/link';
import { motion } from 'framer-motion';

export default function HistoryGrid({ reports }) {
    if (!reports || reports.length === 0) {
        return (
            <div className="text-center py-20 bg-muted/5 rounded-xl border border-dashed border-border w-full">
                <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-4 opacity-50" />
                <h3 className="text-xl font-medium mb-2">No history found</h3>
                <p className="text-muted-foreground mb-6">You haven't scanned any documents yet.</p>
                <Link href="/dashboard" className="text-primary hover:underline">
                    Start a New Scan
                </Link>
            </div>
        )
    }

    // Download report as text file
    const handleDownload = (report) => {
        const content = `
PlagDetect Plagiarism Report
============================
Document: ${report.document?.filename || 'Untitled'}
Date: ${new Date(report.createdAt).toLocaleDateString()}
Originality Score: ${Math.round(report.originalityScore)}%

Status: ${report.originalityScore > 80 ? 'Original Content' : report.originalityScore > 50 ? 'Some Similarity Detected' : 'Significant Plagiarism Detected'}

Report ID: ${report.id}
Generated by PlagDetect
        `.trim();

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `PlagDetect-Report-${report.id.slice(0, 8)}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    // Share report
    const handleShare = async (report) => {
        const shareData = {
            title: 'PlagDetect Report',
            text: `Check out my plagiarism report: ${Math.round(report.originalityScore)}% originality`,
            url: `${window.location.origin}/dashboard/results/${report.id}`
        };

        if (navigator.share) {
            try {
                await navigator.share(shareData);
            } catch (err) {
                // User cancelled or error
                console.log('Share cancelled');
            }
        } else {
            // Fallback: copy to clipboard
            try {
                await navigator.clipboard.writeText(shareData.url);
                alert('Link copied to clipboard!');
            } catch (err) {
                alert('Could not share. Please copy the URL manually.');
            }
        }
    };

    return (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 py-6">
            {reports.map((report, idx) => (
                <motion.div
                    key={report.id}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: idx * 0.05, duration: 0.3 }}
                    className="group"
                >
                    {/* Simple Card - No 3D effect */}
                    <div className="bg-card border border-border rounded-xl p-5 h-full flex flex-col transition-shadow duration-200 hover:shadow-lg hover:shadow-primary/5">
                        {/* Header */}
                        <div className="flex items-start justify-between mb-4">
                            <div className="flex-1 min-w-0">
                                <h3 className="font-semibold text-foreground truncate">
                                    {report.document?.filename || 'Untitled Document'}
                                </h3>
                                <p className="text-xs text-muted-foreground flex items-center gap-1 mt-1">
                                    <Calendar className="w-3 h-3" />
                                    {new Date(report.createdAt).toLocaleDateString()}
                                </p>
                            </div>
                        </div>

                        {/* Score Display */}
                        <div className={`flex-1 rounded-lg p-6 flex items-center justify-center mb-4 ${report.originalityScore > 80
                                ? 'bg-green-500/10'
                                : report.originalityScore > 50
                                    ? 'bg-yellow-500/10'
                                    : 'bg-red-500/10'
                            }`}>
                            <div className="text-center">
                                <h2 className={`text-4xl font-bold ${report.originalityScore > 80
                                        ? 'text-green-500'
                                        : report.originalityScore > 50
                                            ? 'text-yellow-500'
                                            : 'text-red-500'
                                    }`}>
                                    {Math.round(report.originalityScore)}%
                                </h2>
                                <p className="text-xs uppercase tracking-wider text-muted-foreground mt-1">
                                    Originality
                                </p>
                            </div>
                        </div>

                        {/* Actions */}
                        <div className="flex items-center justify-between pt-3 border-t border-border">
                            <Link
                                href={`/dashboard/results/${report.id}`}
                                className="text-sm text-primary hover:underline flex items-center gap-1"
                            >
                                View Details <ArrowRight className="w-3 h-3" />
                            </Link>

                            <div className="flex items-center gap-2">
                                <button
                                    onClick={() => handleShare(report)}
                                    className="p-2 rounded-lg hover:bg-muted transition-colors"
                                    title="Share"
                                >
                                    <Share2 className="w-4 h-4 text-muted-foreground" />
                                </button>
                                <button
                                    onClick={() => handleDownload(report)}
                                    className="p-2 rounded-lg hover:bg-muted transition-colors"
                                    title="Download"
                                >
                                    <Download className="w-4 h-4 text-muted-foreground" />
                                </button>
                            </div>
                        </div>
                    </div>
                </motion.div>
            ))}
        </div>
    );
}
